version: '3'

services:
  db:
    #image: mongo:4.0.4
    image: mongo
    container_name: db
    restart: always
    env_file: .env
    ports:
      - "27017:27017"

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - "db"

networks:
  app-network:
    driver: bridge
